### PR TITLE
Rollout for Java reference class page improvement

### PR DESCRIPTION
**Pull request by xmdanni**
This PR is to rollout massive changes for Java reference class page improvement: [work item](https://dev.azure.com/ceapex/Engineering/_workitems/edit/425554). The improvement includes:

- Huge UI improvement on class webpages
- Move member content into class page (member page will be deleted)

Change count for the rollout on August 22:
- Modified Files: 573
- Deleted Files: 3138

This PR also includes all the necessary redirection (from deleted member page to related class page) for all the monikers. Randomly checked for redirection: all passed.

### CODE REVIEW

**Comment by JasonWHowell** [comment]
@jasongroce can you please spot-check the formatting and structure changes? I realize the long-term goal here, but trying to unblock Matthew Trilby-Bassett who is coordinating the Java SDK across many repos.

**Comment by JasonWHowell** [comment]
I see a typo here: https://review.docs.microsoft.com/en-us/java/api/com.microsoft.store.partnercenter.analytics.customeranalyticscollectionoperations?view=partnercenter-java-latest&branch=pr-en-us-72#moniker-applies-to

Applies To:
Microsoft.Store.PartnerCener

**Comment by JasonWHowell** [comment]
The Moniker is fixed:
image

**Comment by JasonWHowell** [comment]
@jasongroce there are new build warnings. Was that something related to your changes or they just bubbled up suddenly?

**Comment by jasongroce** [comment]
@JasonWHowell The xref warnings have been [this commit](https://buildapi.docs.microsoft.com/Output/Commit/32dbdb78-ef3e-d720-6668-27874f7b2281/202208230821213529-smoke-test/BuildReport?accessString=1781fa1bff07c21f08972c8cb3caa2aac73522c926210bf1b6faf4e05cecfb14) from the 23rd. I have fixed the absolute link warnings and addressed some other copyediting issues.

@xmdanni Are the xref/link warnings something that can be addressed through a subsequent CI or are these something we should look at fixing (removing) manually?

**Comment by gangzhang-ms** [comment]
> @JasonWHowell The xref warnings have been [this commit](https://buildapi.docs.microsoft.com/Output/Commit/32dbdb78-ef3e-d720-6668-27874f7b2281/202208230821213529-smoke-test/BuildReport?accessString=1781fa1bff07c21f08972c8cb3caa2aac73522c926210bf1b6faf4e05cecfb14) from the 23rd. I have fixed the absolute link warnings and addressed some other copyediting issues.
> 
> @xmdanni Are the xref/link warnings something that can be addressed through a subsequent CI or are these something we should look at fixing (removing) manually?

I think the xref warning is not related to our changes this time. It is a historical issue and now we are working on another [task ](https://ceapex.visualstudio.com/Engineering/_workitems/edit/192481) which may solve this question in the future.

**Pull request merged**
