### PR TITLE
Java SDP migration

### PR DESCRIPTION
**Pull request by anmeng10101**

### CODE REVIEW

**Comment by isaiahwilliams** [comment]
@anmeng10101 any ideas on how to resolve the build errors?

**Comment by anmeng10101** [comment]
@isaiahwilliams , build failed because of the merge conflict.

**Comment by anmeng10101** [comment]
@isaiahwilliams , just refreshed `smoke-test` branch, and the validation looks good now. Please kindly review.

**Comment by anmeng10101** [comment]
merge this pr after confirm with @isaiahwilliams

**Pull request merged**
